### PR TITLE
Add initial doc infrastructure

### LINKED ISSUE #6: Set up documentation infrastructure
- [ ] Add `readthedocs.yml` configurations
- [ ]  Configure the project on readthedocs 
- [ ] Enable PR building on readthedocs

### PR DESCRIPTION
**Pull request by mgrover1**
Fixes #6

### CODE REVIEW

**Comment by mgrover1** [comment]
@andersy005 I have started to put some of the files together/enable readthedocs! Do you have a `conf.py` template you usually use?

**Comment by andersy005** [comment]
> @andersy005 I have started to put some of the files together/enable readthedocs! Do you have a `conf.py` template you usually use?

Take a look at https://github.com/NCAR/xpersist/blob/main/docs/source/conf.py

**Comment by mgrover1** [comment]
Hmmm for some reason it's not installing the package - any idea what I am missing here @andersy005 ?

**Comment by andersy005** [comment]
You may want to move `esm_collections/readthedocs.yml` to the root directory of the repository.

**Review by andersy005 — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
